Task 3.2 complete
Deryck41/Egor_Nikitin_DotNet_Course_2021 pull request #11
Opened 2021-10-08 20:50 UTC by Deryck41

2021-10-08 20:51 UTC, Deryck41 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Задания №3](https://trello.com/c/sDONQO7N/117-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%E2%84%963)

2021-10-25 09:31 UTC, PaShkadun requested changes

2021-10-25 09:31 UTC, PaShkadun commented on Task3-2/Task3-2/Program.cs
> +            while (!int.TryParse(Console.ReadLine(), out size) | size<1)
fix.

2021-10-25 09:31 UTC, PaShkadun commented on Task3-2/Task3-2/Program.cs
> +﻿using System;
![image](https://user-images.githubusercontent.com/71289803/138671363-a97e0740-23c0-4613-b5da-72515490e157.png)

2021-12-05 09:55 UTC, merged