Task 3.3 complete
Deryck41/Egor_Nikitin_DotNet_Course_2021 pull request #12
Opened 2021-10-16 21:39 UTC by Deryck41

2021-10-16 21:40 UTC, Deryck41 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Задания №3](https://trello.com/c/sDONQO7N/117-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%E2%84%963)

2021-10-25 09:34 UTC, PaShkadun requested changes

2021-10-25 09:34 UTC, PaShkadun commented on Task3-3/Task3-3/Program.cs
> +            while (!int.TryParse(Console.ReadLine(), out size) | size<1)
Fix.

2021-10-25 09:34 UTC, PaShkadun commented on Task3-3/Task3-3/Program.cs
> +                for (int j = 0; j < size; j++)
FIx.

2021-10-25 09:34 UTC, PaShkadun commented on Task3-3/Task3-3/Program.cs
> +                if (numberFrequency > maxFrequency && numberFrequency != 1)
Fix.

2021-11-20 13:24 UTC, Deryck41 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Задания №3](https://trello.com/c/sDONQO7N/148-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%E2%84%963)

2021-12-04 11:41 UTC, BitW13 approved these changes

2021-12-04 11:41 UTC, BitW13 commented on Task3-3/Task3-3/Program.cs
> +}
![image](https://user-images.githubusercontent.com/28789651/144708144-d89a8e64-03bc-4597-9a30-b06b7839b2cd.png)

2021-12-05 09:56 UTC, merged