Task3 4
Deryck41/Egor_Nikitin_DotNet_Course_2021 pull request #13
Opened 2021-10-23 17:31 UTC by Deryck41

2021-10-23 17:32 UTC, Deryck41 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Задания №3](https://trello.com/c/sDONQO7N/117-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%E2%84%963)

2021-10-25 09:36 UTC, PaShkadun requested changes

2021-10-25 09:36 UTC, PaShkadun commented on Task3-4/Task3-4/Program.cs
> +            while(!int.TryParse(Console.ReadLine(), out size) | size < 1)
Fix.

2021-10-25 09:36 UTC, PaShkadun commented on Task3-4/Task3-4/Program.cs
> +            for (int i = 0; i < size-1; i++)
Fix.

2021-10-25 09:36 UTC, PaShkadun commented on Task3-4/Task3-4/Program.cs
> +            for (int i = 0; i <size-1; i++)
Fix.

2021-10-25 09:36 UTC, PaShkadun commented on Task3-4/Task3-4/Program.cs
> +            while (!int.TryParse(Console.ReadLine(), out position) | position < 0 | position > size-1)
Fix.

2021-10-25 09:36 UTC, PaShkadun commented on Task3-4/Task3-4/Program.cs
> +            for (int i = size-1; i > position; i--)
Fix.

2021-11-20 13:24 UTC, Deryck41 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Задания №3](https://trello.com/c/sDONQO7N/148-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%E2%84%963)

2021-12-04 11:42 UTC, BitW13 approved these changes

2021-12-04 11:42 UTC, BitW13 commented on Task3-4/Task3-4/Program.cs
> +}
![image](https://user-images.githubusercontent.com/28789651/144708170-c9fe0316-fabc-4c62-bab2-890895412dd5.png)

2021-12-05 09:56 UTC, merged